excerpt_separator: <!--more-->
pygments: true
markdown: kramdown
url: http://sidasay.github.io
title: My Journal
tagline: A log of everyday life
description: My awesome blog with Git
paginate: 5
highlighter: rouge
